---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example
  namespace: default
  labels:
    app: go-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-example
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
        - name: go-example
          image: go-example
          imagePullPolicy: IfNotPresent
          args: []
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
