---
apiVersion: v1
kind: Service
metadata:
  name: go-example
  labels:
    app: go-example
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: go-example
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
